version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly' # You can change it to "daily" or "monthly" depending on your preference
    versioning-strategy: 'increase' # Options: "increase", "lockfile-only", "auto"
    # Disable
    # open-pull-requests-limit: 0
