name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        id: check_dependabot
        run: |
          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            echo "This PR is from Dependabot."
            echo "::set-output name=mergeable::true"
          else
            echo "This PR is not from Dependabot."
            echo "::set-output name=mergeable::false"
          fi

      - name: Wait for status checks to pass
        if: steps.check_dependabot.outputs.mergeable == 'true'
        run: |
          echo "Waiting for status checks to pass..."
          sleep 15  # or use GitHub API to check status checks

      - name: Auto-merge PR
        if: steps.check_dependabot.outputs.mergeable == 'true'
        uses: "pascalgn/automerge-action@v0.15.0"
        with:
          merge-method: "squash"  # Use "merge" or "rebase" depending on your preference
