name: Auto Merge Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # or the default branch of your repo
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' # Ensure the PR is from Dependabot

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Merge PR
      run: gh pr merge ${{ github.event.pull_request.number }} --merge --auto
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
